### PR TITLE
[FFM-5087]: Java SDK to use gradle

### PR DESCRIPTION
**Pull request by akiraqb**
```
[FFM-5087]: Java SDK to use gradle

# What is this commit changing e.g. adding new parameter to API
 ### What:
Previous mvn build/dependency management tool will be complemented by gradle
# Why is this change happening, e.g. goals, use cases, stories, etc.?
 ### Why:
To simplify and modernise dependency management and build mechanism
# Testing - how is the commit tested.  If unit tests have been updated/add check the box.
 ### Testing:
Locally, It will also be tested on the relevant build pipelines.
```

[FFM-5087]: https://harness.atlassian.net/browse/FFM-5087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by akiraqb** [comment]
I think when it comes to the gradle that I hope should be it.
Please feel free to comment and give it a go yourself and tell me if I have missed anything.
I think the pipeline needs to be changed to eventually use `./gradlew clean buuild --refresh-dependencies`

**Review by andybharness — APPROVED** [review]
Looks good

**Comment by akiraqb** [comment]
Investigating a little bit more the problem with the codeQL, turns out both "gradle" and "maven" generated files for ApiClient are identical. That can indicating that the problem was not introduced now but was not picked up in the other versions of the SDK due to different file location?

**Comment by akiraqb** [comment]
The codeQL stage is not executing anymore

**Comment by akiraqb** [comment]
After updating Gradle dependencies, codeQL started pointing at files in "/target/" - that could indicate mvn generated files?

**Comment by akiraqb** [comment]
Attempted to exclude path from the codeQL but that only works for some languages

**Pull request closed without merging**
